### PR TITLE
Update to Ember & Ember-cli 3.10

### PR DESCRIPTION
**Pull request by cibernox**
It also updates broccoli-funnel, broccoli-merge-trees, ember-cli-babel, regenerator-runtime

Since this will require node 6, it may qualify for a version bump, depending if you consider removing an unsupported node version a breaking change.

### CODE REVIEW

**Comment by cibernox** [comment]
@machty ping!

**Comment by machty** [comment]
Thank you so much, happy to merge!

As far as bumping the version, it was a big debacle last time we bumped 0.9 to 0.10, and tbh I don't really understand all the tradeoffs, leaning towards keeping it on 0.10, but curious as to your thoughts.

**Comment by cibernox** [comment]
As far as I can tell, no one will notice anything. The update to babel7 should be transparent and perhaps help reduce node_modules if all other dependencies are in babel7 too. Newer broccoli plugins should be faster.

I'd release a patch version.

**Comment by machty** [comment]
@cibernox I'd merged this thinking this was the ember-concurrency repo heh. 

Currently e-c's [dependency](https://github.com/machty/ember-concurrency/blob/master/package.json#L48) on this repo specifies `"ember-maybe-import-regenerator": "^0.1.6"`

Should I change that to "^0.1.7" after releasing 0.1.7?

I feel like I'll never grasp how people evaluate these kinds of decisions :/

**Comment by cibernox** [comment]
I don't think you need to update, people will get the dependency whenever they update their dependencies.

**Comment by cibernox** [comment]
@machty fwiw, I also created a PR to update ember-concurrency: https://github.com/machty/ember-concurrency/pull/297

**Comment by josemarluedke** [comment]
Can someone publish a new version that contains this change? Looking to get ember-cli-babel v7 and above.

**Comment by maxfierke** [comment]
> Can someone publish a new version that contains this change? Looking to get ember-cli-babel v7 and above.
> 
> cc/ @maxfierke

I'll check with Alex to see if he can give me access. However, my understanding is that this package doesn't do anything in Babel 7 as-is (different plugin names for regenerator) and that given the broad support for generator functions at this point in time, it can probably be omitted. (For instance, ember-concurrency v2 doesn't even depend on it anymore).

**Pull request merged**
